### ISSUE TITLE
You could get better speed with binary font

### ISSUE THREAD

**Issue by dglaude** [recantha/picopicorder#4]
There is a new way and better format to deal with font.
It require to convert to PCF font.
It might take less memory, less space, make less fragmentation of the memory, maybe be faster to display.
It can be as simple as to convert your file and load the new file...

https://learn.adafruit.com/custom-fonts-for-pyportal-circuitpython-display/convert-to-pcf

**Comment by recantha** [comment]
Is a .bdf not a binary font, then? I assumed the b was for binary... Doh!

**Comment by dglaude** [comment]
Maybe it is bitmap font and not binary font.
Also I don't see any B in PCF acronym, so much for TLA!

There is also a way to "preload" the character you plan to use with load_glyphs.
It is supposed to cost memory and increase speed... I guess.

**Comment by recantha** [comment]
Interesting! The PCF is FOUR TIMES the size of the bdf. However, it is a lot quicker to render. I've also put load_glyphs in, and that's sped it up, too! Think I'll keep it in there! Thank you! :-)
